---
functional:
-Пользователь должен иметь возможность искать товары по ключевому слову или категории
-Пользователь должен иметь возможность фильтровать товары
-Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
-Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
-Пользователь должен иметь возможность переключить язык интерфейса
-Сайт должен иметь локализацию (перевод) на русский и английский языки
non-functional:
-Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
-Сайт должен быть безопасным и защищать данные пользователя
-Сайт должен иметь мобильную версию
-Сайт нужно протестировать на совместимость с последними версиями браузеров
-Важно, чтобы сайт мог обрабатывать большое количество трафика
-Сайт должен быть доступен на различных устройствах
implicit:
-Невозможность ввода отрицательной цены
-При указании количества товаров нельзя указать отрицательное число 
-Цена в корзине должна совпадать с ценой на странице товара
-все дополнительные сборы( доставка сертификата, выезд на дом и т.д) должны быть показаны до окончательного подтверждения заказа
-У пользователя должна быть возможность очистить корзину 
-Индикация наличия товара должна быть динамичной и правдивой
